title: SwissPedHealth PipeDev Docs
description: SwissPedHealth PipelineDev Docs made with Jeykll using the Just the Docs theme.
theme: just-the-docs

url: https://swisspedhealth-pipelinedev.github.io

aux_links:
  Docs Repo: https://github.com/SwissPedHealth-PipelineDev/docs
  Project: https://SwissPedHealth.ch
